<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <AssemblyName>FluentSakhrDictionary-Setup</AssemblyName>
    <ApplicationManifest>installer.manifest</ApplicationManifest>
    <ApplicationIcon>../src/FluentSakhrDictionary/app.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="payload.zip" />
    <Resource Include="logo.png" />
  </ItemGroup>
</Project>
